USE PC

CREATE TABLE PC (
	code INT PRIMARY KEY,
	model VARCHAR(50) FOREIGN KEY REFERENCES Product(model) NOT NULL,
	speed DECIMAL(4,0) NOT NULL,
	ram DECIMAL(4, 0) NOT NULL ,
	hd DECIMAL(3, 0) NOT NULL ,
	cd VARCHAR(3) NOT NULL ,
	price FLOAT NOT NULL 
)
