USE PC

CREATE TABLE Laptop (
	code INT PRIMARY KEY,
	model VARCHAR(50) FOREIGN KEY REFERENCES Product(model) NOT NULL,
	speed DECIMAL(4,0) NOT NULL,
	ram DECIMAL(4, 0) NOT NULL ,
	hd DECIMAL(3, 0) NOT NULL ,
	price FLOAT NOT NULL,
	screen VARCHAR(50) NOT NULL
)